### ISSUE TITLE
Use layout2?

### ISSUE THREAD

**Issue by bootstraponline** [applitools/Eyes.Selenium.Ruby#10]
I don't see [layout 2](https://github.com/applitools/Eyes.Selenium.Ruby/blob/2e0038b4db97fc967a57adb63644e1a44289b6b2/lib/eyes_selenium/eyes/match_level.rb#L1) in the match_level file. Should I just use a hard coded string to activate this match mode?

**Comment by danielputerman** [comment]
Hi, yes, since that match level is still considered beta, we haven't released it in all SDKs yet. I'll merge the relevant PR.
