### ISSUE TITLE
745 rubocop offenses detected

### ISSUE THREAD

**Issue by bootstraponline** [applitools/Eyes.Selenium.Ruby#13]
It'd be nice to [setup rubocop](https://github.com/bbatsov/rubocop) and run that on Travis to ensure consistency of style. The appium ruby gem uses [rubocop](https://travis-ci.org/appium/ruby_lib/builds/61843250) in CI.

**Comment by lbeder** [comment]
Fixed.

**Comment by bootstraponline** [comment]
Awesome!
