### ISSUE TITLE
undefined method error in version 2.17.0

### ISSUE THREAD

**Issue by tourdedave** [applitools/Eyes.Selenium.Ruby#19]
Seeing a failure when using `@eyes.check_window("")`. Here's the error:

```sh
undefined method `extract_viewport_from_browser' for #<Applitools::Base::Dimension:0x007fb1b2eeaf50> (NoMethodError)
```

No issue with version 2.16.0.

**Comment by lbeder** [comment]
Which tests were you running?

**Comment by tourdedave** [comment]
No tests in the project. Tests in a project of mine. I amended the copy to be more clear.

**Comment by lbeder** [comment]
Thanks for reporting. We'll take a look.

**Comment by tourdedave** [comment]
Great! Let me know if you want me to send over some examples for reproducing.

**Comment by lbeder** [comment]
Could you please include the entire exception trace? I find it hard to reproduce the issue.

**Comment by tourdedave** [comment]
Next time I'm at my computer I will.

You should be able to reproduce it by cloning my repo, bumping the eyes_selenium version in the Gemfile to `2.17`, doing a `bundle install`, and running the suite (e.g., `bundle exec cucumber`).

Right now it's set to `2.16`.

**Comment by bootstraponline** [comment]
`bundle exec cucumber -b` produced the full stack trace which I've posted [to this gist](https://gist.github.com/bootstraponline/6fe1d2d97f3ee8f784a7).

**Comment by lbeder** [comment]
Thanks everyone! The issue was fixed and a new version should be released soon.
