### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by bootstraponline** [applitools/Eyes.Selenium.Ruby#21]
Can you [tag the releases](https://github.com/blog/1547-release-your-software)? GitHub shows that [there's never been a release](https://github.com/applitools/Eyes.Selenium.Ruby/releases).

**Comment by lbeder** [comment]
Sure!

**Comment by bootstraponline** [comment]
thanks! :smile:

**Comment by danielputerman** [comment]
Done, we'll keep on tagging. Thanks for the feedback!
