### ISSUE TITLE
uninitialized constant Applitools::Selenium::SimpleDelegator (NameError)

### ISSUE THREAD

**Issue by wjordan** [applitools/Eyes.Selenium.Ruby#25]
This error started appearing when I tried to upgrade the `eyes_selenium` gem from 2.5.0 to 2.23.0 on an Ubuntu 15.04 workstation:
```
$ ruby -e "require 'eyes_selenium';"
/home/will/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/eyes_selenium-2.23.0/lib/applitools/selenium/element.rb:2:in `<module:Selenium>': uninitialized constant Applitools::Selenium::SimpleDelegator (NameError)
	from /home/will/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/eyes_selenium-2.23.0/lib/applitools/selenium/element.rb:1:in `<top (required)>'
	from /home/will/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/eyes_selenium-2.23.0/lib/eyes_selenium.rb:5:in `require'
	from /home/will/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/eyes_selenium-2.23.0/lib/eyes_selenium.rb:5:in `block in <module:Applitools>'
	from /home/will/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/eyes_selenium-2.23.0/lib/eyes_selenium.rb:5:in `each'
	from /home/will/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/eyes_selenium-2.23.0/lib/eyes_selenium.rb:5:in `<module:Applitools>'
	from /home/will/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/eyes_selenium-2.23.0/lib/eyes_selenium.rb:1:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
```

This was most likely a regression caused by 279df972476a4ba67d94eb89b12475fd5139b0c2 - the codebase likely has an implicit load-order requirement (see e.g. 33a820fcb0ced99e683f260d46fcc11e9e0b56be) which [`Dir[]`](http://ruby-doc.org/core-2.2.2/Dir.html#method-c-5B-5D) may seem to satisfy on some platforms (e.g. OSX), but the order in which results are returned "depends on your system", so it will not be consistent across platforms. An easy workaround is to append `.sort` to the result, which I will submit in a pull request as it seems to work to fix this issue in my case.

**Comment by danielputerman** [comment]
Thanks! Sorry for the late reply :) I'll check out the PR and merge it soon.

**Comment by danielputerman** [comment]
Merged PR.
