### ISSUE TITLE
Uninitialized constant `Applitools::Base`

### ISSUE THREAD

**Issue by anurag90x** [applitools/Eyes.Selenium.Ruby#29]
When trying to run cucumber with eyes-selenium, that error gets thrown from `server_connector.rb`. It throws that error as soon as it encounters the line `Applitools::Base::ServerConnector`. Any ideas as to how to fix this?

**Comment by lbeder** [comment]
Thanks for reporting this. It doesn't seem to reproduce on our side, so is there any chance that you could set up a very small sample project, where it reproduces for you, and we'll fix it as soon as possible?

**Comment by danielputerman** [comment]
Can you please provide log and stack trace?  You can turn logs on by adding the following line (assuming your _Eyes_ instance is named _eyes_):
`eyes.log_handler = Logger.new(STDOUT)`

**Comment by danielputerman** [comment]
@anurag90x were you able to find a solution?
