### ISSUE TITLE
Applitools::NewTestError

### ISSUE THREAD

**Issue by bootstraponline** [applitools/Eyes.Selenium.Ruby#5]
Isn't the default suppose to [automatically create new baselines](http://support.applitools.com/customer/portal/articles/1391329-new-automatic-creation-of-new-baselines)? I don't want to manually approve each one.

```
 1) Applitools visits the marketing page
     Failure/Error: @eyes.close
     Applitools::NewTestError:
       'testing 123' of 'test'. Please approve the new baseline at https://eyes.applitools.com/app/sessions/251971185223403
     # /Users/user/.rvm/gems/ruby-2.2.2/gems/eyes_selenium-2.13.0/lib/eyes_selenium/eyes/eyes.rb:221:in `close'
```

**Comment by danielputerman** [comment]
Yes, that's the default, and your test should have been saved automatically. Was that not the case? 
The message you referred to is meant to encourage users to verify the baselines (as it's generally considered good practice) and will appear even if the test was automatically saved.

**Comment by bootstraponline** [comment]
Oh, I didn't expect the error to appear even if it was auto saved. Now I know. This isn't a bug then. Thanks for the response.
