### ISSUE TITLE
Eyes Selenium not working after selenium 3.1 update

### ISSUE THREAD

**Issue by msiddique** [applitools/Eyes.Selenium.Ruby#51]
In selenium 3.1 update, the DriverExtensions::HasInputDevices class was removed from driver extensions. 
Below is the commit that caused the issue.
https://github.com/SeleniumHQ/selenium/commit/2cd8007f8d694ffc278296aa896d6f01a676cd0c

**Comment by danielputerman** [comment]
Thanks @msiddique! We're currently working on a fix, which should be available very soon.

**Comment by danielputerman** [comment]
Solved in 1d5ebfd7b189b046ee011dc117d50b901fffdd59 and pushed to RubyGems (version 2.39.0).
