### ISSUE TITLE
Track dependencies with gemnasium.com

### ISSUE THREAD

**Issue by bootstraponline** [applitools/Eyes.Selenium.Ruby#8]
gemnasium.com offers a free Ruby badge that will tell you when the dependencies are out of date. You can see how it's used in the Appium ruby gem:

`[![Dependency Status](https://gemnasium.com/appium/ruby_lib.svg)](https://gemnasium.com/appium/ruby_lib)`
[![Dependency Status](https://gemnasium.com/appium/ruby_lib.svg)](https://gemnasium.com/appium/ruby_lib)

It'd be nice to have this integration setup & added to the readme.

**Comment by danielputerman** [comment]
Accepted the PR. Thanks!

**Comment by bootstraponline** [comment]
The PR I sent was for the rubygems badge (which tracks the released version of the gem, not dependencies). The gemnasium integration requires setting up GitHub hooks (requires owner level permission on the repo) so it's not something I can submit a PR for.

**Comment by danielputerman** [comment]
Woops, thought that was the pull request :)

**Comment by danielputerman** [comment]
Yea I just noticed. We'll incorporate gemnasium very soon as well.

**Comment by lbeder** [comment]
Done via d39dbd2aad.
