### ISSUE TITLE
Setup tests to run automatically on Travis

### ISSUE THREAD

**Issue by bootstraponline** [applitools/Eyes.Selenium.Ruby#9]
It'd be nice if the Eyes.Selenium.Ruby specs ran automatically on Travis. Sauce has a free plan for open source projects.

**Comment by danielputerman** [comment]
I Definitely agree. We're currently doing a major revision of SDK, and one of the first assignments is automatic testing using Travis. This Should be available within the next few weeks.

**Comment by lbeder** [comment]
Done via d39dbd2aad.
